blank_issues_enabled: false
contact_links:
  - name: Keith himself
    url: https://keithrozario.com
    about: Please ask and answer questions here.
  - name: Security Issues
    url: mailto:keith+githubsecurity@keithrozario.com
    about: Please report security vulnerabilities here.