update:
  all

search: False
requirements:
- packages/aiobotocore/requirements.txt:
  update: all
  pin: true
- packages/aiodns/requirements.txt:
  update: all
  pin: true
- packages/aiohttp/requirements.txt:
  update: all
  pin: true
- packages/ansible/requirements.txt:
  update: all
  pin: true
- packages/arrow/requirements.txt:
  update: all
  pin: true
- packages/bcrypt/requirements.txt:
  update: all
  pin: true
- packages/beautifulsoup4/requirements.txt:
  update: all
  pin: true
- packages/boltons/requirements.txt:
  update: all
  pin: true
- packages/boto3/requirements.txt:
  update: all
  pin: true
- packages/Cerberus/requirements.txt:
  update: all
  pin: true
- packages/construct/requirements.txt:
  update: all
  pin: true
- packages/elasticsearch/requirements.txt:
  update: all
  pin: true
- packages/envelopes/requirements.txt:
  update: all
  pin: true
- packages/ffmpeg-python/requirements.txt:
  update: all
  pin: true
- packages/flashtext/requirements.txt:
  update: all
  pin: true
- packages/google-auth-oauthlib/requirements.txt:
  update: all
  pin: true
- packages/google-auth/requirements.txt:
  update: all
  pin: true
- packages/graphene/requirements.txt:
  update: all
  pin: true
- packages/grequests/requirements.txt:
  update: all
  pin: true
- packages/grpcio/requirements.txt:
  update: all
  pin: true
- packages/gspread/requirements.txt:
  update: all
  pin: true
- packages/idna/requirements.txt:
  update: all
  pin: true
- packages/itsdangerous/requirements.txt:
  update: all
  pin: true
- packages/jellyfish/requirements.txt:
  update: all
  pin: true
- packages/jsonrpclib/requirements.txt:
  update: all
  pin: true
- packages/kafka-python/requirements.txt:
  update: all
  pin: true
- packages/ldap3/requirements.txt:
  update: all
  pin: true
- packages/loguru/requirements.txt:
  update: all
  pin: true
- packages/nltk/requirements.txt:
  update: all
  pin: true
- packages/numpy/requirements.txt:
  update: all
  pin: true
- packages/opencv-python-headless/requirements.txt:
  update: all
  pin: true
- packages/openpyxl/requirements.txt:
  update: all
  pin: true
- packages/pandas/requirements.txt:
  update: all
  pin: true
- packages/pickleDB/requirements.txt:
  update: all
  pin: true
- packages/Pillow/requirements.txt:
  update: all
  pin: true
- packages/PyJWT/requirements.txt:
  update: all
  pin: true
- packages/pymongo/requirements.txt:
  update: all
  pin: true
- packages/PyMUPDF/requirements.txt:
  update: all
  pin: true
- packages/PyMySQL/requirements.txt:
  update: all
  pin: true
- packages/PyNaCl/requirements.txt:
  update: all
  pin: true
- packages/pyOpenSSL/requirements.txt:
  update: all
  pin: true
- packages/pyparsing/requirements.txt:
  update: all
  pin: true
- packages/pytesseract/requirements.txt:
  update: all
  pin: true
- packages/python-docx/requirements.txt:
  update: all
  pin: true
- packages/python-Levenshtein-wheels/requirements.txt:
  update: all
  pin: true
- packages/pytz/requirements.txt:
  update: all
  pin: true
- packages/PyYAML/requirements.txt:
  update: all
  pin: true
- packages/requests/requirements.txt:
  update: all
  pin: true
- packages/scipy/requirements.txt:
  update: all
  pin: true
- packages/simplejson/requirements.txt:
  update: all
  pin: true
- packages/SQLAlchemy/requirements.txt:
  update: all
  pin: true
- packages/tablib/requirements.txt:
  update: all
  pin: true
- packages/tinydb/requirements.txt:
  update: all
  pin: true
- packages/tldextract/requirements.txt:
  update: all
  pin: true