update:
  all

search: False
requirements:
  - requests/latest/requirements.txt:
      update: all
      pin: True
  - beautifulsoup4/latest/requirements.txt:
      update: all
      pin: True
  - elasticsearch/latest/requirements.txt:
      update: all
      pin: True
  - bcrypt/latest/requirements.txt:
      update: all
      pin: True
  - pymongo/latest/requirements.txt:
      update: all
      pin: True
  - pyOpenSSL/latest/requirements.txt:
      update: all
      pin: True
  - aiohttp/latest/requirements.txt:
      update: all
      pin: True
  - ffmpeg-python/latest/requirements.txt:
      update: all
      pin: True
  - tldextract/latest/requirements.txt:
      update: all
      pin: True
  - construct/latest/requirements.txt:
      update: all
      pin: True
  - Pillow/latest/requirements.txt:
      update: all
      pin: True
  - pytesseract/requirements.txt:
      update: all
      pin: True
  - spacy/requirements.txt:
      update: all
      pin: True 

label_prs: update