update:
  all

search: False
requirements:
  - packages/requests/latest/requirements.txt:
      update: all
      pin: True
  - packages/beautifulsoup4/latest/requirements.txt:
      update: all
      pin: True
  - packages/elasticsearch/latest/requirements.txt:
      update: all
      pin: True
  - packages/bcrypt/latest/requirements.txt:
      update: all
      pin: True
  - packages/pymongo/latest/requirements.txt:
      update: all
      pin: True
  - packages/pyOpenSSL/latest/requirements.txt:
      update: all
      pin: True
  - packages/aiohttp/latest/requirements.txt:
      update: all
      pin: True
  - packages/ffmpeg-python/latest/requirements.txt:
      update: all
      pin: True
  - packages/tldextract/latest/requirements.txt:
      update: all
      pin: True
  - packages/construct/latest/requirements.txt:
      update: all
      pin: True
  - packages/Pillow/latest/requirements.txt:
      update: all
      pin: True
  - packages/pytesseract/requirements.txt:
      update: all
      pin: True
  - packages/spacy/latest/requirements.txt:
      update: all
      pin: True 
  - packages/boto3/latest/requirements.txt:
      update: all
      pin: True
  - packages/PyMuPDF/latest/requirements.txt:
      update: all
      pin: True
  - packages/pytz/latest/requirements.txt:
      update: all
      pin: True

label_prs: update