service: Klayers-python37

frameworkVersion: "=1.40.0"

plugins:
  - serverless-iam-roles-per-function
provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'default'}
  region: ${file(../infra/terraform.tfvars.json):aws_region.${self:provider.stage}}
  profile: ${file(../infra/terraform.tfvars.json):aws_profile.${self:provider.stage}}
  versionFunctions: false
  logRetentionInDays: 1

custom:
  awsRegion: ${self:provider.region}

  # environment variables
  s3LayersName: ${ssm:/${self:service.name}/${self:provider.stage}/s3bucket_layers}
  s3DomainsArn: ${ssm:/${self:service.name}/${self:provider.stage}/s3bucket_layers_arn}
  
  dbTempName: ${ssm:/${self:service.name}/${self:provider.stage}/dynamodb_layers_table}
  dbTempArn: ${ssm:/${self:service.name}/${self:provider.stage}/dynamodb_layers_table_arn}


functions:
  install:
    handler: install.main
    runtime: python3.7
    layers:
      - arn:aws:lambda:${self:provider.region}:113088814899:layer:Klayers-python37-packaging:1
      - arn:aws:lambda:${self:provider.region}:113088814899:layer:Klayers-python37-requests:4
    timeout: 30
    memorySize: 512
    environment:
      BUCKET_NAME: ${self:custom.s3LayersName}

package:
  exclude:
    - package-lock.json
    - node_modules/**
    - serverless.yml
    - .gitignore
    - .serverless
